spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/assignmentdb
    username: root
    password: MyNewPass
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    filter:
      order: 10


jwt:
  secret: hellojustsomething

